name: Publish to GitHub Packages
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
      
    steps:
    
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
                   
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          
      - name: Publish to GitHub Packages
        run: mvn -B deploy -DskipTests -Pgithub-repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
