
name: Project Site

on: 
  release: 
    types: [published, unpublished, created, edited, deleted]
  
  push:
    branches:
      - master
    paths:
      - 'src/site/**'
      - 'pom.xml'
   
jobs:  
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        path: nom-tam-fits
        
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        path: site
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Build, test, and deploy with Maven
      run: mvn clean site
      working-directory: ./nom-tam-fits
        
    - name: Update site
      run: |
        cp -a nom-tam-fits/target/site/* site/
        cd site
        git config --global user.email "$GITHUB_JOB+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions"
        git add -A
        git commit -m "[automated site update]"
        git push
