
name: Update Site

on: 
  release: 
    types: [published, unpublished, created, edited, deleted]
  
  push:
    paths:
      - "src/site/**"
   
jobs:  
  build:

    runs-on: ubuntu-latest
    env:
      CI_DEPLOY_USERNAME: git
    steps:
    - uses: actions/checkout@v2
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Build, test, and deploy with Maven
      run: mvn site-deploy --settings settings.xml


