
name: Update Site

on: 
  release: [published, created, edited]
  
  push:
    paths:
      - "src/site/**"
   
jobs:  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: nom-tam-fits
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Build, test, and deploy with Maven
      run: mvn clean site-deploy
      working-directory: ./nom-tam-fits


