# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Test

on: 
  push:
    paths:
      - 'src/main/java/**'
      - 'pom.xml'
  
  pull_request:
    paths:
      - 'src/main/java/**'
      - 'pom.xml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: nom-tam-fits
        
    - name: Check out blackbox images 
      uses: actions/checkout@v2
      with:
        repository: nom-tam-fits/blackbox-images
        path: blackbox-images
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Build and test with Maven
      run: mvn -B test jacoco:report --file pom.xml
      working-directory: ./nom-tam-fits
      
    - name: Log coverage percentage
      continue-on-error: true
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
       
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      continue-on-error: true
      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
        working-directory: ./nom-tam-fits
        files: ./target/site/jacoco/jacoco.xml
        fail_ci_if_error: false
        flags: unittests
        name: codecov
        verbose: true

    - name: SNAPSHOT release
      if: ${{ github.repository_owner == 'nom-tam-fits' }}
      continue-on-error: true
      env:
        CI_DEPLOY_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        CI_DEPLOY_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      uses: qcastel/github-actions-maven-release@v1.12.27
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        gpg-enabled: true
        gpg-key-id: ${{ secrets.GPG_KEY_ID }}
        gpg-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
        maven-args: '-Prelease-profile --settings settings.xml'
      
      
#    - name: Upload JaCoCo coverage report
#      uses: actions/upload-artifact@v2
#      with:
#        name: jacoco-report
#       path: ./nom-tam-fits/target/site/jacoco/

